import type { Metadata } from "next";
import { Geist_Mono, JetBrains_Mono, Poppins } from "next/font/google";
import "@/app/globals.css";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "800"],
});


const jetBrainisMono = JetBrains_Mono({
  variable: "--font-jet-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${jetBrainisMono.variable} ${geistMono.variable} ${poppins.variable} antialiased w-full`}
      >
        <div className="flex h-screen w-screen flex-row">
      {/* <SessionNavBar /> */}
      <main className="flex h-screen grow flex-col overflow-auto">
        {children}
      </main>
    </div>
        
      </body>
    </html>
  );
}
